version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./hyperbolic_llm.db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: npm start